### ISSUE TITLE
Unable to make a new tweet :)

### ISSUE THREAD

**Issue by dmilith** [louipc/turses#3]
Now I'm using Python 3.6.7. I'm trying same tweet as before: http://s.verknowsys.com/f0ba11d9866c38b988eb90fe370a6212.png
:) Hitting Enter does nothing (no matter how many times I hit Enter).

**Comment by dmilith** [comment]
Quite interesting, cause counter was <160, but it was blocking send.

**Comment by louipc** [comment]
On Mon 22 Oct 2018 13:50 -0700, Daniel (dmilith) Dettlaff wrote:
> Quite interesting, cause counter was <160, but it was blocking send.

Sorry this client was made to follow the original 140 limit. I havent done any
patches to make it up to date. It's just here so people can use it if they like.
Or fork.

**Comment by booxter** [comment]
@louipc Hi! thanks for saving the project in your fork. Do you have plans to maintain the code base going forward? It seems like you are not particularly interested in it as per your last comment here, but I would like to clarify it before I formally fork it and take over maintenance.

Thanks.

**Comment by louipc** [comment]
On Thu 23 May 2019 22:56 -0700, Ihar Hrachyshka wrote:
> @louipc Hi! thanks for saving the project in your fork. Do you have plans to
> maintain the code base going forward? It seems like you are not particularly
> interested in it as per your last comment here, but I would like to clarify it
> before I formally fork it and take over maintenance.

Hello. Thanks for your initiative. I encourage you to fork and maintain the
codebase in the future. I will mirror your changes. I do not have plans to
maintain the code other than "whenever I get to it". Thanks.

**Comment by booxter** [comment]
@louipc thanks for accepting my patches! Do you have control of pypi package? I think it would make sense to release another version with the fixes. We could do it here on GitHub but Pypi would still carry an older version. What do you think? Or should we create a new package with a different name?

**Comment by louipc** [comment]
On Fri 24 May 2019 21:47 -0700, Ihar Hrachyshka wrote:
> Do you have control of pypi package?
> I think it would make sense to release another version with the fixes. We
> could do it here on GitHub but Pypi would still carry an older version. What
> do you think? Or should we create a new package with a different name?

No I dont have any access to that. The original developer deleted his github,
so I was the only updated repo on github. Maybe you can make a new package or
try to get access to pypi.  Cheers.

**Comment by louipc** [comment]
booxters patches fixed this problem
